### ISSUE TITLE
"Connected, no Internet" warning

### ISSUE THREAD

**Issue by Adarma** [ET-CS/EZ-Wifi-Notification#2]
Sometimes a routers internet connection stops, but the Wifi remains active. There is no warning for this, so it is easy to accidentally use Mobile Data.

Is it possible to auto disable Mobile data when connected to a specific WiFi network, and auto enable when disconnected?

Is it possible to implement a "Connected, no Internet" warning?
This is the massage in the WiFi list when connected to WiFi, but the internet connection is down.

**Comment by ET-CS** [comment]
Hi,

I am not maintaining this project anymore but will be glad to merge and upload to google Play! any pull request.
You are welcome to send one for this issue.
