### ISSUE TITLE
Only plays system sounds

### ISSUE THREAD

**Issue by ghost** [ET-CS/EZ-Wifi-Notification#3]
I tried to use mp3 and wav file from \Notifications folder, stored there by a ringtone maker app.
Your app plays it in the sound selection dialog but not for the notification.
Do you except a special sound format or folder ?
Android 6.0.1 on Samsung S5

**Comment by ET-CS** [comment]
Hi,

I am not maintaining this project anymore but will be glad to merge and upload to google Play! any pull request.
You are welcome to send one for this issue.
